"""delete column weight

Revision ID: 99b5c447b6b6
Revises: c434016a2f66
Create Date: 2025-11-21 23:46:24.398237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b5c447b6b6'
down_revision = 'c434016a2f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
